### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by gozelus** [aliyun/aliyun-mns-go-sdk#6]
sdk报错：receiveMessage err for ali_mns response status error,code: SignatureDoesNotMatch, message: The request signature we calculated does not match the signature you provided. Check your key and signing method., resource: queues/videoTagCallback/messages

**Comment by Alllfred** [comment]
已解决：库中使用的`queue_url`格式与api文档中并不一致，希望可以在exampl中添加正确的url生成格式。
